### ISSUE TITLE
Compressed public address mistake.

### ISSUE THREAD

**Issue by zimage** [grondilu/bitcoin-bash-tools#1]
I think you have an error when computing the public address for a compressed keypair. It doesn't match with what openssl does at least. I have included a patch

``` diff
diff --git a/bitcoin.sh b/bitcoin.sh
old mode 100644
new mode 100755
index 1ea0f0b..9f67947
--- a/bitcoin.sh
+++ b/bitcoin.sh
@@ -91,7 +91,7 @@ newBitcoinKey() {
            else y_parity="03"
            fi
            uncompressed_addr="$(hexToAddress "$(perl -e "print pack q(H*), q(04$X$Y)" | hash160)")"
-           compressed_addr="$(hexToAddress "$(perl -e "print pack q(H*), q(03$X$y_parity)" | hash160)")"
+           compressed_addr="$(hexToAddress "$(perl -e "print pack q(H*), q($y_parity$X)" | hash160)")"
            echo ---
             echo "secret exponant:          0x$exponant"
            echo "public key:"
```

**Comment by grondilu** [comment]
I don't remember the format for compressed address.  I need to review this and then I'll correct accordingly.  Thanks for pointing out the issue.

**Comment by zimage** [comment]
Here's a reference from bitcointalk: https://bitcointalk.org/index.php?topic=129652.msg1687617#msg1687617

**Comment by grondilu** [comment]
Yes now I've reviewed the code, it did not make sense to reuse a 03 literal prefix since the "$y_parity" variable is supposed to be used for that.  I'll use your patch.  Thanks.
