### ISSUE TITLE
Find back public keys from private key

### ISSUE THREAD

**Issue by ghost** [grondilu/bitcoin-bash-tools#10]
Hello,

Sorry to disturb you, but i'm just beginning with bitcoin keys.

I was planning to use this script in order to find "lost" pub keys from private, but I can't manage to put it to work by using this script...

Could you explain to me how to achieve what i'm looking for?

Thank you for your time, and for your response...

**Comment by grondilu** [comment]
sorry I did not answer, I wasn't much involved in this project anymore at the time.

Now I'm back to it but the code has changed dramatically so I'm closing this issue for now.  Feel free to open a new one if need be.
