### ISSUE TITLE
求助！谢谢

### ISSUE THREAD

**Issue by ppho99** [grondilu/bitcoin-bash-tools#13]
一、我查询了版本号，是3.2.57

192:~ hufeng$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.

二、运行更新命令，但更新不成功

192:~ hufeng$ brew update && brew install bash
-bash: brew: command not found

需要怎样解决？

**Comment by grondilu** [comment]
brew is a command line utility that is not related to this project in any way.  See alternate ways to update your bash.
