### ISSUE TITLE
bech32 support

### ISSUE THREAD

**Issue by kxcd** [grondilu/bitcoin-bash-tools#14]
Hi grondilu, this is a great project and excellent implementation you have, I was wondering if it is possbile to also create the bech32 address?  I am not sure if that is even feasible.  I checked previous issues and commits and it hasn't come up yet as far as I can tell.

**Comment by grondilu** [comment]
It certainly is possible, but would require some work.   Maybe some day I'll find motivation to do it.

**Comment by BobDodds** [comment]
[bech32, bech32m,](https://bitcoin.stackexchange.com/questions/101117/what-problems-identified-with-bech32-addresses-have-been-resolved-with-the-updat) both co-existing so it's two standards. It sounds unfinished.

**Comment by grondilu** [comment]
considering it done now, mostly since bip-0084 is now supported.
