### ISSUE TITLE
Can't run the script

### ISSUE THREAD

**Issue by Zorsor** [grondilu/bitcoin-bash-tools#16]
Hi, I've tried to download and run the script on Ubuntu 18.04 LTS (and older Ubuntu versions) with no luck. It's a bootable USB evaluation version of Ubuntu. I've tried several commands on the terminal with no luck. I need some help.

**Comment by grondilu** [comment]
What error message do you get if any ?

**Comment by Zorsor** [comment]
I don't get any error messages at all. It just won't run.

**Comment by grondilu** [comment]
What do you mean it won't run ?  If you mean it does nothing, let me point at that the script just loads functions in memory, you then must run these functions individually, as shown in the synopsis.

**Comment by Zorsor** [comment]
I got it to work now. I did it the wrong way. I downloaded the script and tried to run it by double clicking. Thank you for your help!
