### ISSUE TITLE
Mis-identification of bash version

### ISSUE THREAD

**Issue by DavidCWGA** [grondilu/bitcoin-bash-tools#3]
```
$ echo $BASH_VERSION
4.2.45(2)-release
$ bitcoin.sh
This script requires bash version 4 or above.
bitcoin.sh: line 20: return: can only `return' from a function or sourced script
```

This is on OS X 10.8.4 with bash compiled from MacPorts, if it makes any difference.

**Comment by grondilu** [comment]
What do you get with:

$ echo ${BASH_VERSINFO[0]}   # notice that this is BASH_VERSINFO and not BASH_VERSION

?

**Comment by DavidCWGA** [comment]
```
$ echo ${BASH_VERSINFO[0]}
4
```

**Comment by grondilu** [comment]
Weird, it should not raise the version exception, then.   Try this, just to be sure:

$ ((BASH_VERSINFO[0] < 4)) && echo "you're running a bash version prior to 4"

**Comment by DavidCWGA** [comment]
No output to that.

**Comment by grondilu** [comment]
Ok, no output means it recognizes the version as being 4 or above.  I suspect the shebang is not respected and it uses an other version of bash than the one you run on command line.   Pull bash-bitcoin-tools, make sure bitcoin.sh starts with:

```
if ((BASH_VERSINFO[0] < 4))
then
    echo "This script requires bash version 4 or above." >&2
    exit 538510
fi
```

and type:

$ source bitcoin.sh

It should not say anything and exit quietly.

**Comment by DavidCWGA** [comment]
Yep, my fault. My shell bash is not at /bin/bash, and the version there was old.

Sorry!
