### ISSUE TITLE
[Feature request] verify Bitcoin signed messages.

### ISSUE THREAD

**Issue by Shinoa-Fores** [grondilu/bitcoin-bash-tools#45]
This is defacto one of my favourite Bitcoin-related projects, and I share the hope to have"offline wallet" capabilities using common GNU tools, I have been following since reading [this bitcointalk thread](https://bitcointalk.org/index.php?topic=2461.0) long ago.

For some time have been trying to make functions for signing/verifying BTC messages using openssl. While this is possible when the keys exist in pem format and one operates on binary sig - it works. Still trying to wrap head around how to verify standard compact BTC sigs using bash/tools alone.

Thanks again for these very useful tools.

**Comment by grondilu** [comment]
> I have been following since reading [this bitcointalk thread](https://bitcointalk.org/index.php?topic=2461.0) long ago.

Wow that is indeed an old thread.  Amazingly enough, I knew about bitcoin for only one month when I wrote this post.

I think the initial goal of an offline wallet using only bash and common utilities is now possible, especially with the advent of HD wallets.   As you may have noticed I can now export a bitcoin private key in PEM format, which should make it possible to use openssl to sign or verify transactions (it would be simpler and more reliable than by using my dc library).

It would still require a lot of work though, so it will probably not happen soon, as I currently lack motivation to work on that.

Maybe in an other ten years lol
