### ISSUE TITLE
bitcoinAddress produces wrong public key

### ISSUE THREAD

**Issue by willcbanks** [grondilu/bitcoin-bash-tools#47]
$ bitcoinAddress 5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip78q4h8QmfB6MwMuF1

gives:

1JTUng4hGuPqbbjbkuoyS6BnEXKii6aXV7

which is NOT the ~~public key~~ _bitcoin address_ associated with this private key.

The ~~public key~~ _bitcoin address_ is:

1NpYjtLira16LfGbGwZJ5JbDPh3ai9bjf4

Any idea why it gives the wrong ~~public key~~ _bitcoin address_?

**Comment by grondilu** [comment]
$ base58 -d <<<5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip78q4h8QmfB6MwMuF1 |xxd -p -c 41
    800000000000000000000000000000000000000000000000007cce5efdaccf68083fc3e5bc

It can be seen that there is no 01 flag before the checksum.  So the public point is meant to be uncompressed while creating the bitcoin address.

 * wif : 5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip78q4h8QmfB6MwMuF1
 * hex : 800000000000000000000000000000000000000000000000007cce5efdaccf68083fc3e5bc
 * private key : 0000000000000000000000000000000000000000000000007cce5efdaccf6808
 * uncompressed public point : 0465ec2994b8cc0a20d40dd69edfe55ca32a54bcbbaa6b0ddcff36049301a545795a1b76ab01e9edd0de24157ceff77bcb0f615560b250b365a5d435873eaa4625
 * hash160 : bf7c262e71dada34929bccdf27a93a77acecd93c
 * bitcoinAdress : 1JTUng4hGuPqbbjbkuoyS6BnEXKii6aXV7

1NpYjtLira16LfGbGwZJ5JbDPh3ai9bjf4 is what you get when you use the _compressed_ public point, which is not what this WIF indicates you should do.

**Comment by grondilu** [comment]
closing, as I'm fairly sure this is resolved.
