### ISSUE TITLE
encodeBase58() appears to be inserting a newline character into the output

### ISSUE THREAD

**Issue by michaelklopot** [grondilu/bitcoin-bash-tools#7]
output appears like so:

bash-4.2$ encodeBase58 00a839606e0a6dfb8c73195e36e7adfde1ddd7130e
1
3Lw2EX9dFL9EgpuGnyVJR59zfr8M

This is under bash-4.2 on OS X Mavericks.
This bug in turn affects hexToAddress() and newBitcoinKey(), providing confusing output...

**Comment by grondilu** [comment]
I can't reproduce this as I don't have a OS X machine.   encodeBase58 is a fairly simple function, though.  Try tweaking it a bit to see what makes this line return show up.

For instance, try with very simple string, such as "00".  Does it still print a line return?

**Comment by grondilu** [comment]
base58 encode/decode code was rewritten extensively so this error should not occur anymore.  Feel free to open an other issue otherwise.
